Repository ARUP-CAS/aiscr-webamcr, pull requests merged in 2022-10, with the labels that each got.

#691 Bug/650 pas edit coordinates
  webclient/pas/templates/pas/coor.html
  webclient/static/js/mapa_pas.js
Labels: bug / maintanance

#693 Task/310 novy symbol mereni
  webclient/static/img/ruler-bold-32.png
  webclient/static/img/triangular-ruler.png
  webclient/static/js/arch_z_detail_map.js
  webclient/static/js/leaflet.measure.js
  webclient/static/js/mapa_basic.js
  webclient/static/js/mapa_basic_grey.js
Labels: enhancement, map

#694 Fix: issue 293 geonames
  webclient/arch_z/templates/arch_z/detail.html
  webclient/dokument/templates/dokument/coor_doc.html
  webclient/dokument/templates/dokument/coor_model_3D.html
  webclient/oznameni/templates/oznameni/index.html
  webclient/pas/templates/pas/coor.html
  webclient/pian/templates/pian/detail.html
  webclient/projekt/templates/projekt/create.html
  webclient/projekt/templates/projekt/detail.html
  webclient/projekt/templates/projekt/edit.html
  webclient/static/css/leaflet-search.css
  webclient/static/css/leaflet-search.mobile.css
  webclient/static/img/loader.gif
  webclient/static/img/search-icon-mobile.png
  webclient/static/img/search-icon.png
  webclient/static/js/arch_z_detail_map.js
  webclient/static/js/leaflet-search-geocoder.js
  webclient/static/js/leaflet-search.js
  webclient/static/js/mapa_basic.js
  webclient/static/js/mapa_basic_grey.js
  webclient/templates/map.html
Labels: enhancement, map

#698 bug/640-oprava-prejmenovani-souboru
  webclient/dokument/views.py
Labels: DONE

#718 Oprava Dockerfile pro cp translaci
  Dockerfile-production
Labels: DONE

#722 Feature/326 filtrace rozbalovani
  webclient/dokument/filters.py
  webclient/pas/filters.py
  webclient/projekt/filters.py
Labels: DONE
